[general]
live_config_reload = true
import = [
  "~/.config/alacritty/shell.toml",
  "~/.config/alacritty/env.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/hint.toml",
  "~/.config/alacritty/window.toml",
  "~/.config/alacritty/keyboard.toml",
  "~/.config/alacritty/theme.toml",
]
