#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

themes_dir="$HOME/.config/borders/themes"

if [ -z "$PREFERS_COLOR_SCHEME" ];
then
  apple_interface_style_status="$(defaults read -g AppleInterfaceStyle &>/dev/null && echo $?)"
  if [ "$apple_interface_style_status" = "0" ];
  then
    PREFERS_COLOR_SCHEME="dark"
  else
    PREFERS_COLOR_SCHEME="light"
  fi
fi

if [ "$PREFERS_COLOR_SCHEME" = "light" ];
then
  # shellcheck source=./themes/light.sh
  source "$themes_dir/light.sh"
else
  # shellcheck source=./themes/dark.sh
  source "$themes_dir/dark.sh"
fi

options=(
  active_color="$JANKY_BORDERS_ACTIVE_COLOR"
  ax_focus=off
  hidpi=on
  inactive_color="$JANKY_BORDERS_INACTIVE_COLOR"
  style=square
  width=5.0
)

borders "${options[@]}"
