if [[ $(type -t dotfiles::lib::constants::paths::loaded) == function ]];
then
  return
fi

DOTFILES_LIB_CONSTANTS_PATHS_FILE="$(realpath -- "${BASH_SOURCE[0]}")"
export DOTFILES_LIB_CONSTANTS_PATHS_FILE

DOTFILES_LIB_CONSTANTS_DIR="$(dirname "$DOTFILES_LIB_CONSTANTS_PATHS_FILE")"
export DOTFILES_LIB_CONSTANTS_DIR

DOTFILES_LIB_DIR="$(dirname "$DOTFILES_LIB_CONSTANTS_DIR")"
export DOTFILES_LIB_DIR

DOTFILES_LIB_EXTENSIONS_DIR="${DOTFILES_LIB_DIR}/extensions"
export DOTFILES_LIB_EXTENSIONS_DIR

DOTFILES_LIB_EXTENSIONS_ASDF_DIR="${DOTFILES_LIB_EXTENSIONS_DIR}/asdf"
export DOTFILES_LIB_EXTENSIONS_ASDF_DIR

DOTFILES_LIB_EXTENSIONS_ASDF_TOOLS_DIR="${DOTFILES_LIB_EXTENSIONS_ASDF_DIR}/tools"
export DOTFILES_LIB_EXTENSIONS_ASDF_TOOLS_DIR

DOTFILES_LIB_EXTENSIONS_ETC_DIR="${DOTFILES_LIB_EXTENSIONS_DIR}/etc"
export DOTFILES_LIB_EXTENSIONS_ETC_DIR

DOTFILES_DIR="$(dirname "$DOTFILES_LIB_DIR")"
export DOTFILES_DIR

DOTFILES_BIN_DIR="${DOTFILES_DIR}/bin"
export DOTFILES_BIN_DIR

DOTFILES_CONFIG_DIR="${DOTFILES_DIR}/config"
export DOTFILES_CONFIG_DIR

DOTFILES_SCRIPTS_DIR="${DOTFILES_DIR}/scripts"
export DOTFILES_SCRIPTS_DIR

DOTFILES_THIRD_PARTY_DIR="${DOTFILES_DIR}/third_party"
export DOTFILES_THIRD_PARTY_DIR

dotfiles::lib::constants::paths::loaded() {
  return 0
}
