shell_integration enabled
shell /opt/homebrew/bin/tmux new -A

env COLORTERM=truecolor
env INHERIT_SYSTEM_THEME=1

font_family      family='JetBrainsMonoNL Nerd Font Mono' postscript_name=JetBrainsMonoNLNFM-Regular
bold_font        family='JetBrainsMonoNL Nerd Font Mono' style=SemiBold
italic_font      family='JetBrainsMonoNL Nerd Font Mono' style=Italic
bold_italic_font family='JetBrainsMonoNL Nerd Font Mono' style='SemiBold Italic'

font_size 12.0

disable_ligatures always

modify_font cell_width 90%
modify_font cell_height 1px

hide_window_decorations yes

window_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.window}{progress_percent}{title}"

confirm_os_window_close 0

tab_bar_style separator
tab_separator " ░ "

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

background_opacity 0.98
dim_opacity 0.4

macos_titlebar_color system
macos_option_as_alt yes
macos_thicken_font 0.05
macos_show_window_title_in none
macos_colorspace displayp3

clipboard_control write-primary write-clipboard no-append

update_check_interval 0
enable_audio_bell = no

# hex(ord("%"))
map cmd+d send_text all \x01\x25

# hex(ord("\""))
map shift+cmd+d send_text all \x01\x22

# hex(ord("c"))
map cmd+t send_text all \x01\x63

# hex(ord("x") & 0x1F)
map cmd+w send_text all \x01\x18

map cmd+left send_key all ctrl+a ctrl+a
map cmd+right send_key ctrl+e

map cmd+backspace send_key ctrl+u
map cmd+delete send_key ctrl+k

map cmd+enter send_key enter
